MOCK_CLIENTS = [
    {
        "id": "CLT-001",
        "nom": "Dupont Transports",
        "siret": "12345678901234",
        "type": "expéditeur",
        "statut": "actif",
        "contact": {
            "nom": "Jean Dupont",
            "email": "jean.dupont@dupont-transports.fr",
            "telephone": "+33 1 23 45 67 89",
        },
        "adresse": {
            "rue": "12 rue de la Paix",
            "code_postal": "75001",
            "ville": "Paris",
            "pays": "France",
        },
    },
    {
        "id": "CLT-002",
        "nom": "ACME Logistics",
        "siret": "98765432109876",
        "type": "destinataire",
        "statut": "actif",
        "contact": {
            "nom": "Marie Martin",
            "email": "m.martin@acme-logistics.fr",
            "telephone": "+33 4 56 78 90 12",
        },
        "adresse": {
            "rue": "5 avenue des Industries",
            "code_postal": "69001",
            "ville": "Lyon",
            "pays": "France",
        },
    },
    {
        "id": "CLT-003",
        "nom": "Bertrand & Fils",
        "siret": "55566677788899",
        "type": "expéditeur",
        "statut": "actif",
        "contact": {
            "nom": "Pierre Bertrand",
            "email": "p.bertrand@bertrand-fils.fr",
            "telephone": "+33 5 67 89 01 23",
        },
        "adresse": {
            "rue": "22 boulevard Industriel",
            "code_postal": "33000",
            "ville": "Bordeaux",
            "pays": "France",
        },
    },
    {
        "id": "CLT-004",
        "nom": "Marchetti Import Export",
        "siret": "11122233344455",
        "type": "transitaire",
        "statut": "actif",
        "contact": {
            "nom": "Lucie Marchetti",
            "email": "l.marchetti@marchetti-ie.fr",
            "telephone": "+33 3 45 67 89 01",
        },
        "adresse": {
            "rue": "8 quai du Port",
            "code_postal": "13001",
            "ville": "Marseille",
            "pays": "France",
        },
    },
    {
        "id": "CLT-005",
        "nom": "Transport Durand",
        "siret": "77788899900011",
        "type": "expéditeur",
        "statut": "inactif",
        "contact": {
            "nom": "Thomas Durand",
            "email": "t.durand@transport-durand.fr",
            "telephone": "+33 2 34 56 78 90",
        },
        "adresse": {
            "rue": "15 rue de la Gare",
            "code_postal": "44000",
            "ville": "Nantes",
            "pays": "France",
        },
    },
]

MOCK_CHARGEMENTS = [
    {
        "id": "CHG-2026-00891",
        "reference_client": "REF-DPT-2026-001",
        "client_id": "CLT-001",
        "client_nom": "Dupont Transports",
        "statut": "en_cours",
        "type": "FTL",
        "origine": {"ville": "Paris", "code_postal": "75001", "adresse": "12 rue de la Paix"},
        "destination": {"ville": "Lyon", "code_postal": "69001", "adresse": "5 avenue des Industries"},
        "date_enlevement": "2026-04-12",
        "date_livraison_prevue": "2026-04-13",
        "date_livraison_reelle": None,
        "marchandise": "Matériel électronique",
        "poids_kg": 450,
        "volume_m3": 3.2,
        "transporteur": "Carrier Express",
        "chauffeur": "Marc Leblanc",
        "plaque_vehicule": "AB-123-CD",
        "notes": [],
        "incidents": [],
    },
    {
        "id": "CHG-2026-00892",
        "reference_client": "REF-DPT-2026-002",
        "client_id": "CLT-001",
        "client_nom": "Dupont Transports",
        "statut": "livre",
        "type": "LTL",
        "origine": {"ville": "Paris", "code_postal": "75008", "adresse": "48 avenue Hoche"},
        "destination": {"ville": "Marseille", "code_postal": "13002", "adresse": "10 quai de la Joliette"},
        "date_enlevement": "2026-04-08",
        "date_livraison_prevue": "2026-04-10",
        "date_livraison_reelle": "2026-04-10",
        "marchandise": "Produits alimentaires",
        "poids_kg": 1200,
        "volume_m3": 8.5,
        "transporteur": "FastRoute",
        "chauffeur": "Sophie Moreau",
        "plaque_vehicule": "EF-456-GH",
        "notes": ["Livraison effectuée sans problème"],
        "incidents": [],
    },
    {
        "id": "CHG-2026-00893",
        "reference_client": "ACME-2026-007",
        "client_id": "CLT-002",
        "client_nom": "ACME Logistics",
        "statut": "en_retard",
        "type": "FTL",
        "origine": {"ville": "Bordeaux", "code_postal": "33000", "adresse": "22 bd Industriel"},
        "destination": {"ville": "Paris", "code_postal": "75015", "adresse": "2 rue du Commerce"},
        "date_enlevement": "2026-04-10",
        "date_livraison_prevue": "2026-04-11",
        "date_livraison_reelle": None,
        "marchandise": "Pièces automobiles",
        "poids_kg": 3200,
        "volume_m3": 15.0,
        "transporteur": "LogiTrans",
        "chauffeur": "David Petit",
        "plaque_vehicule": "IJ-789-KL",
        "notes": [],
        "incidents": [
            {
                "date": "2026-04-11",
                "type": "retard",
                "description": "Panne mécanique sur l'A10 — véhicule de remplacement en cours de déploiement",
            }
        ],
    },
    {
        "id": "CHG-2026-00894",
        "reference_client": "ACME-2026-008",
        "client_id": "CLT-002",
        "client_nom": "ACME Logistics",
        "statut": "planifie",
        "type": "FTL",
        "origine": {"ville": "Lyon", "code_postal": "69003", "adresse": "8 rue de la Part-Dieu"},
        "destination": {"ville": "Strasbourg", "code_postal": "67000", "adresse": "15 route du Rhin"},
        "date_enlevement": "2026-04-15",
        "date_livraison_prevue": "2026-04-16",
        "date_livraison_reelle": None,
        "marchandise": "Textiles",
        "poids_kg": 800,
        "volume_m3": 6.0,
        "transporteur": "EuroTrans",
        "chauffeur": None,
        "plaque_vehicule": None,
        "notes": [],
        "incidents": [],
    },
    {
        "id": "CHG-2026-00895",
        "reference_client": "REF-BRT-2026-012",
        "client_id": "CLT-003",
        "client_nom": "Bertrand & Fils",
        "statut": "livre",
        "type": "LTL",
        "origine": {"ville": "Bordeaux", "code_postal": "33000", "adresse": "22 bd Industriel"},
        "destination": {"ville": "Toulouse", "code_postal": "31000", "adresse": "40 allée Jean-Jaurès"},
        "date_enlevement": "2026-04-07",
        "date_livraison_prevue": "2026-04-08",
        "date_livraison_reelle": "2026-04-08",
        "marchandise": "Vins et spiritueux",
        "poids_kg": 2400,
        "volume_m3": 4.8,
        "transporteur": "Carrier Express",
        "chauffeur": "Anne Rousseau",
        "plaque_vehicule": "MN-012-OP",
        "notes": ["Livraison en bonne condition"],
        "incidents": [],
    },
    {
        "id": "CHG-2026-00896",
        "reference_client": "MIE-2026-003",
        "client_id": "CLT-004",
        "client_nom": "Marchetti Import Export",
        "statut": "annule",
        "type": "FTL",
        "origine": {"ville": "Marseille", "code_postal": "13001", "adresse": "8 quai du Port"},
        "destination": {"ville": "Paris", "code_postal": "75010", "adresse": "5 rue du Faubourg"},
        "date_enlevement": "2026-04-09",
        "date_livraison_prevue": "2026-04-10",
        "date_livraison_reelle": None,
        "marchandise": "Matériaux de construction",
        "poids_kg": 5000,
        "volume_m3": 22.0,
        "transporteur": None,
        "chauffeur": None,
        "plaque_vehicule": None,
        "notes": ["Annulé par le client — commande annulée"],
        "incidents": [],
    },
    {
        "id": "CHG-2026-00897",
        "reference_client": "REF-DPT-2026-003",
        "client_id": "CLT-001",
        "client_nom": "Dupont Transports",
        "statut": "en_cours",
        "type": "FTL",
        "origine": {"ville": "Paris", "code_postal": "75012", "adresse": "30 avenue Daumesnil"},
        "destination": {"ville": "Lille", "code_postal": "59000", "adresse": "20 rue Nationale"},
        "date_enlevement": "2026-04-13",
        "date_livraison_prevue": "2026-04-14",
        "date_livraison_reelle": None,
        "marchandise": "Équipements informatiques",
        "poids_kg": 600,
        "volume_m3": 4.5,
        "transporteur": "NordExpress",
        "chauffeur": "Paul Simon",
        "plaque_vehicule": "QR-345-ST",
        "notes": [],
        "incidents": [],
    },
]
